ALTER TABLE courts ADD COLUMN IF NOT EXISTS lawyer_room_phone TEXT;
ALTER TABLE courts ADD COLUMN IF NOT EXISTS municipalities TEXT[];
ALTER TABLE courts ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE courts ADD COLUMN IF NOT EXISTS working_hours TEXT;